### ISSUE TITLE
Move project to pyproject.toml

### ISSUE THREAD

**Issue by antoinevg** [greatscottgadgets/python-usb-protocol#35]

**Comment by sarnold** [comment]
Did you mean skip setuptools and move to pyproject.toml with a newer build backend, eg hatch or something else?  I still have a PR in my fork with setup.cfg/pyproject.toml that could convert to hatch pretty easily, including a hatch plugin for dynamic versioning. (uses setuptools_scm under the hood)

**Comment by antoinevg** [comment]
For now it's just migrating `setup.py` to a minimal setuptools-based `pyproject.toml` to bring it in line with the rest of the GSG Python repositories -- e.g. https://github.com/greatscottgadgets/facedancer/blob/main/pyproject.toml

Thank you for #37 by the way, there's a lot of functionality in there I'd like to see across all the GSG repositories but, as you can imagine, it's going to be somewhat of a gradual process rolling it out while keeping things consistent.

**Comment by antoinevg** [comment]
Closed by: https://github.com/greatscottgadgets/python-usb-protocol/pull/39
